# Generated by Django 4.0 on 2022-05-23 08:18

from django.db import migrations, models
import nepali_datetime_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Shift', models.CharField(choices=[('Regular', 'Regular')], max_length=50)),
                ('HR_Year', models.CharField(choices=[('2078/79', '2078/79'), ('2079/80', '2079/80')], max_length=8)),
                ('nepali_date', nepali_datetime_field.models.NepaliDateField()),
                ('Holiday_Title', models.CharField(choices=[('Public', 'Public Holiday'), ('International', 'International'), ('Active', 'Active Holiday'), ('Other', 'Other Holiday')], max_length=50)),
                ('Status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('T', 'Terminated'), ('B', 'Blacklisted')], max_length=50)),
            ],
        ),
    ]
