# Generated by Django 4.0 on 2022-05-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrcalendar',
            options={'verbose_name': 'HRCalendar', 'verbose_name_plural': 'HRCalendar'},
        ),
    ]
